name: Run tests

on:
    push:
      branches:
        - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/checkout@v3
        with:
          java-version: '8'
          distribution: 'zulu'
        
      - name: Build project with maven
        working-directory: .
        run: |
          mvn test 
      
       - name: Create report
        working-directory: .
        run: |
          mvn jacoco:report

        
	# your task: figure out the remainings steps 
	# that match your selected language. 
	# Hint: follow slide 15 for inspiration
	# You should first find an action that sets up the environment
	# for your selected programming language. 
	# You should then set up the steps to run similar to how you run
	# them locally

